import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/assets/logo.jpeg" />
      </Head>
      <div> Empty project</div>
    </div>
  );
}
